AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
  RunRailsCops: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
AsciiComments:
  Enabled: false
